### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'enable_lora'

### ISSUE THREAD

**Issue by hxu105** [zjunlp/Mol-Instructions#14]
Howdy,

Thank you for sharing this amazing work, and I am having some hard time implementing your checkpoints. I do the `peft_model = PeftModel.from_pretrained(model, "zjunlp/llama-molinst-molecule-7b")` (the model is using 'meta-llama/Llama-2-7b-chat-hf': `model =  AutoModelForCausalLM.from_pretrained('meta-llama/Llama-2-7b-chat-hf')`, and it returns me this error `TypeError: __init__() got an unexpected keyword argument 'enable_lora'`. Could you help to take a look at it?

Many thanks!

**Comment by Fangyinfff** [comment]
1. The Lora weight and base model do not match. When the weight is 'zjunlp/llama-molinst-molecule-7b', Llama should be used as the base model; when the weight is 'zjunlp/llama2-molinst-molecule-7b', Llama-2 should be used as the base model. 

2. Did you refer to the content in 'https://github.com/zjunlp/Mol-Instructions/tree/main/demo' when running? The issue might be due to the wrong version of the package. Please replace it with the correct version of the package. Additionally, refer to https://github.com/huggingface/peft/issues/1087.

**Comment by hxu105** [comment]
Thank you, changing the peft version solves the problem.
