### ISSUE TITLE
pyarrow.lib.ArrowInvalid when loading data

### ISSUE THREAD

**Issue by btyu** [zjunlp/Mol-Instructions#5]
Hi! I am using the fine-tuning code. The command in demo/README.md cannot work properly now, as the newest pytorch would overlap the installed 1.12.0. I installed pytorch==1.13.1 instead of 1.12.0, and finally got everything installed without error. However, when I fine-tune on the molecule data, an error always happens: 

```
Failed to read file 'data/property_prediction.json' with error <class 'pyarrow.lib.ArrowInvalid'>: Could not convert '-0.2253' with type str: tried to convert to double
```

I guess it's because of the incompatibility of packages. Could you please help me fix this problem or provide some insights?

Thank you very much.

**Comment by Fangyinfff** [comment]
Hello,

Thank you for bringing this to my attention. To be honest, I am not quite sure about the root cause either. However, I have re-cleaned the data and updated it at [huggingface](https://huggingface.co/datasets/zjunlp/Mol-Instructions/tree/main/data), as well as modified the [data loading code](https://github.com/zjunlp/Mol-Instructions/blob/main/demo/finetune.py#L205-L208). Theoretically, this should circumvent the issue (I have tested it myself, and it runs successfully). You are welcome to re-download the data and try running the code again. Please feel free to reach out if you require further assistance.

**Comment by btyu** [comment]
It is now working. Thank you sincerely for your quick response and help.
